### ISSUE TITLE
Implement Object Calisthenics

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.detekt#9]
- [x] 1. One level of indentation per method https://github.com/TWiStErRob/net.twisterrob.detekt/commit/9c43b4993eb8870711105848703f06847c56a897
- [x] 2. Don’t use the ELSE keyword https://github.com/TWiStErRob/net.twisterrob.detekt/commit/6dd7c3d0df6bec9a8bb22655600df2e440eeb81a
- [x] 3. Wrap all primitives and Strings https://github.com/TWiStErRob/net.twisterrob.detekt/commit/730402e1ee0307f3203345305eef52dfe49ef338
- [ ] 4. First class collections https://github.com/TWiStErRob/net.twisterrob.detekt/issues/8
- [x] 5. One dot per line https://github.com/TWiStErRob/net.twisterrob.detekt/commit/23b8280e9c69f9bf2ef3f176ede68ed07cb2c8cb
- [ ] 6. Don’t abbreviate https://github.com/TWiStErRob/net.twisterrob.detekt/issues/5
- [x] 7. Keep all entities small https://github.com/TWiStErRob/net.twisterrob.detekt/commit/f67120fbb1594a2c21d10d7154a5b53cdc8efe1d
- [ ] 8. No classes with more than two instance variables https://github.com/TWiStErRob/net.twisterrob.detekt/issues/4
- [ ] 9. No getters/setters/properties https://github.com/TWiStErRob/net.twisterrob.detekt/issues/6
- [ ] 10. https://github.com/TWiStErRob/net.twisterrob.detekt/issues/7
